CREATE TABLE client_satisfaction (
    response_id INT IDENTITY(1,1) PRIMARY KEY,
    profile_id INT NULL,
    timestamp DATETIME NOT NULL,
    date_previous_doctor_visit DATETIME,
    services_provided NVARCHAR(MAX),
    health_self_assessment INT,
    self_health_assessment_narrative NVARCHAR(MAX),
    stress_self_assessment INT,
    stress_self_assessment_narrative NVARCHAR(MAX),
    mental_self_assessment INT,
    mental_self_assessment_narrative NVARCHAR(MAX),
    physical_self_assessment INT,
    physical_self_assessment_narrative NVARCHAR(MAX),
    overall_impression NVARCHAR(MAX),
    medical_needs_met BIT,
    provider_expectations BIT,
    medical_needs_met_narrative NVARCHAR(MAX),
    outreach_support BIT,
    outreach_support_narrative NVARCHAR(MAX),
    healthycuts_member NVARCHAR(50),
    movement_medicine_member NVARCHAR(50),
    clinical_trial_interest BIT,
    survey_interest BIT NOT NULL,
    FOREIGN KEY (profile_id) REFERENCES profiles(profile_id)
);